# Generated by Django 2.1.7 on 2019-02-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingredients',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Tags',
            new_name='tags',
        ),
    ]
